my_holidays = {"1":   "Another Friggin Year Day",
               "2":   "Swiss Cheese Day",
               "3":   "Make Macaroni Pictures Day",
               "4":   "Spaghetti Day",
               "5":   "International Verbal Abuse Day",
               "6":   "Extra Cuddles Day",
               "7":   "No Knitting Day",
               "8":   "Bubble Bath Day",
               "9":   "Walk Like an Egyptian Day",
               "10":  "Peculiar People Day",
               "11":  "Spam Spam Spam Spam Spam Day",
               "12":  "Penne in Your Thoughts Day",
               "13":  "Sceptics Day",
               "14":  "Wear a Collander Day",
               "15":  "Unicorn Day",
               "16":  "Nothingness Appreciation Day",
               "17":  "International No Farting Day",
               "18":  "Egg Juggling Day",
               "19":  "Procrastination Day Tomorrow",
               "20":  "Marx Brothers Quote Day",
               "21":  "Ravioli Day",
               "22":  "Quantum Cheese Day",
               "23":  "Get Your Tongue Round Some Linguine Day",
               "24":  "Invent a God Day",
               "25":  "Burns Night",
               "26":  "String Appreciation Day",
               "27":  "Llama Day",
               "28":  "Black Pepper with Everything Day",
               "29":  "Curmudgeons Day",
               "30":  "Exercise Your Brain Day",
               "31":  "Honey Badger Avoidance Day",
               "32":  "Fettucine February",
               "33":  "Groundhog Day",
               "34":  "Ewok Day",
               "35":  "Annoy the Neighbours Day",
               "36":  "Doodle Day",
               "37":  "Self-love Day",
               "38":  "No-Day Day",
               "39":  "Avoid Artichokes Day",
               "40":  "Extraterestial Culture Day",
               "41":  "Paradox Day",
               "42":  "Hide Under the Bed Day",
               "43":  "Darwin Day",
               "44":  "Tortellini Day",
               "45":  "Pretend to be Romantic Day",
               "46":  "Drink More Wine Day",
               "47":  "Platypus Pondering Day",
               "48":  "Hopping Day",
               "49":  "Navel Appreciation Day",
               "50":  "Lentil Sauce Day",
               "51":  "Levitation Day",
               "52":  "Talk to a Goldfish Day",
               "53":  "Appreciate Dragons Day",
               "54":  "Remember the Alamo Day",
               "55":  "Carthaginian Ghost Spotting Day",
               "56":  "Octopus Enjoyment Day",
               "57":  "Lost Pen Day",
               "58":  "Silly Hat Day",
               "59":  "Evil Clown Day",
               "400": "Refuse to believe in this day day",
               "60":  "Narwhal Day",
               "61":  "Tagliatelle Day",
               "62":  "Mulled Wine Day",
               "63":  "Random Day",
               "64":  "Momofuku Ando’s Birthday",
               "65":  "Fusilli Day",
               "66":  "Contradiction Day (No it’s not!)",
               "67":  "Annie Bonny’s Birthday",
               "68":  "Meatball Day",
               "69":  "Wooden Leg Polishing Day",
               "70":  "Douglas Adams Birthday",
               "71":  "Cuddle an Accountant Day",
               "72":  "Cthulhu Contemplation Day",
               "73":  "Pi Day",
               "74":  "Aardvark Appreciation Day",
               "75":  "Kinky Underwear Day",
               "76":  "St. Patricks Day Excuse",
               "77":  "Vodka Day",
               "78":  "Beer Appreciation Day",
               "79":  "Extraterrestrial Abductions Day",
               "80":  "French Bread Day",
               "81":  "Slightly Silly Day",
               "82":  "Pansexual Quantum Toaster Day",
               "83":  "Red Wine Day",
               "84":  "Manatee Appreciation Day",
               "85":  "Make Up Your Own Holiday Day",
               "86":  "Paella Day",
               "87":  "Garden Weeds Appreciation Day",
               "88":  "Cocktail Hour Every Hour Day",
               "89":  "Poke Things with a Pencil Day",
               "90":  "Survived Another Month Day",
               "91":  "All Fools Day",
               "92":  "Existential Angst Day",
               "93":  "Seize a Sausage Day",
               "94":  "Feast of No Saints Day",
               "95":  "Pizza Day",
               "96":  "Impersonate a Frog Day",
               "97":  "Inner Wombat Appreciation Day",
               "98":  "Zoo Day",
               "99":  "Cook Couscous Day",
               "100": "Alfredo Sauce Day",
               "101": "Cheese Fondue Day",
               "102": "Naughty Noodle Day",
               "103": "Believe in Fairies Day",
               "104": "Look up at the Sky Day",
               "105": "Banana Day",
               "106": "Sea Monkey Soup Day",
               "107": "Haiku Day",
               "108": "Nihilism Day",
               "109": "Lager Day",
               "110": "Intergalactic Alien Solidarity Day",
               "111": "Eggnog Avoidance Day",
               "112": "Earth Day",
               "113": "Cynical Bastards Day",
               "114": "Hairball Awareness Day",
               "115": "World Penguin Day",
               "116": "Hug an Australian Day",
               "117": "8640 Seconds Day",
               "118": "Blueberry Pie Day",
               "119": "Dance Day",
               "120": "Achieve Enlightenment Day",
               "121": "No Pants Day",
               "122": "Ramen Day",
               "123": "Pirate Garb Day",
               "124": "Star Wars Day",
               "125": "Ferret Day",
               "126": "Beverage Day",
               "127": "Scurvy Awareness Day",
               "128": "Back Scratching Day",
               "129": "Lost Sock Memorial Day",
               "130": "Wolverine Day",
               "131": "Salvador Dali Day",
               "132": "Limerick Day",
               "133": "Buttocks Day",
               "134": "International Monty Python Day",
               "135": "Bike to Work Day",
               "136": "Skinny Dipping Day",
               "137": "Single Malt Whisky Day",
               "138": "Russell’s Teapot Day",
               "139": "Bolognese Sauce Day",
               "140": "Fetish Day",
               "141": "42 Day",
               "142": "Biological Diversity Day",
               "143": "Turtle Day",
               "144": "Mollusc Day",
               "145": "Towel Day",
               "146": "World Hunger Day",
               "147": "Weasel Tossing Day",
               "148": "Amnesty International Day",
               "149": "Pillow Fight Day",
               "150": "Random Act of Kindness Day",
               "151": "Insect Appreciation Day",
               "152": "Go Barefoot Day",
               "153": "Laugh Like a Bad Guy Day",
               "154": "Mushroom Sauce Day",
               "155": "Cougar Day",
               "156": "Doughnut Day",
               "157": "Adopt a New Phobia day",
               "158": "Captain Jack Sparrow Impersonation Day",
               "159": "Be Annoyingly Cheerful Day",
               "160": "Bathe in Marinara Day",
               "161": "Flirting Day",
               "162": "Fish Day",
               "163": "Be Paranoid Day",
               "164": "Gin Day",
               "165": "Bourbon Day",
               "166": "Bad Joke Day",
               "167": "World Meat-free Day",
               "168": "Contact an Old Friend Day",
               "169": "Now Panic Day",
               "170": "Martini Day",
               "171": "World Juggling Day",
               "172": "World Humanist Day",
               "173": "Marinara Sauce Day",
               "174": "Parrot Pondering Day",
               "175": "Sexual Fantasy Day",
               "176": "Seafarer Day",
               "177": "Carbonara Day",
               "178": "Blue-Footed Booby Day",
               "179": "Tickle Day",
               "180": "Knitting Day",
               "181": "Just Another Day Day",
               "182": "Any Bloody Excuse Day",
               "183": "Pesto Sauce Day",
               "184": "Strange Urges Day",
               "185": "Build a Scarecrow Day",
               "186": "Impersonate an Orc Day",
               "187": "Macaroni Day",
               "188": "Cannelloni Day",
               "189": "Meatball Appreciation Day",
               "190": "Invent a Word Day",
               "191": "Pina Colada Day",
               "192": "World Population Day",
               "193": "Surrealism Day",
               "194": "Geek Appreciation Day",
               "195": "Cow Appreciation Day",
               "196": "Ferret Down Your Trousers Day",
               "197": "Bobby Henderson’s Birthday",
               "198": "Why Not? Day",
               "199": "Waterpistol Day",
               "200": "Daiquiri Day",
               "201": "National Lasagne Day",
               "202": "Primavera Sauce Day",
               "203": "Contemplate the Cosmos Day",
               "204": "Free Hugs Day",
               "205": "Tequila Day",
               "206": "Hot Fudge Sundae Day",
               "207": "White Wine Day",
               "208": "Confuse a Cat Day",
               "209": "Try a New Cheese Day",
               "210": "International Beer Day",
               "211": "Parmesan Day",
               "212": " Real Ale Day",
               "213": "Cartoon Day",
               "214": "Vermicelli Day",
               "215": "Postmodernism Day",
               "216": "Mead Day",
               "217": "Putanesca Sauce Day",
               "218": "Squirrel Spotting Day",
               "219": "International Beer Day",
               "220": " International Cat Day",
               "221": " Invisible Pixy Swatting Day",
               "222": "Lazy Day",
               "223": "Rum Day",
               "224": "Vegetable Sauce Day",
               "225": "Listen To Reggae Day",
               "226": "Think about Infinity Day",
               "227": "Con dom Day",
               "228": "Wave At The Surveillance Cameras Day",
               "229": "Gnocchi Gnawing day.",
               "230": "Poetry Day",
               "231": "Kiss Someone Day",
               "232": "Expensive Rum Day",
               "233": "Apologise Day",
               "234": "Tarantula Teasing Day",
               "235": "Appreciate What You’ve Got Day",
               "236": "Pluto Demotion Grieving Day",
               "237": "Whiskey Sour Day",
               "238": "Women’s Equality Day",
               "239": "Udon Day",
               "240": "More Rum Day",
               "241": "Blobfish Day",
               "242": "Candle in a Winebottle Day",
               "243": "Alter Ego Day",
               "244": "Hobbit Remembrance Day",
               "245": "Nipple Appreciation Day",
               "246": "World No Haggis Day",
               "247": "Rock Appreciation Day",
               "248": "Yodelling Day",
               "249": "Diablo Sauce Day",
               "250": "Old Boy/Girlfiends Remembrance Day",
               "251": "Paradoxically Non-paradoxical Day",
               "252": "Ogle an Orchid Day",
               "253": "Albatross Appreciation Day",
               "254": "Tinfoil Hat Day",
               "255": "Nakedness Appreciation Day",
               "256": "Mosquito Avoidance Day",
               "257": "Despair for the Human Race Day",
               "258": "Irish Coffee Day",
               "259": "Cynicism Appreciation Day",
               "260": "Wear Purple Day",
               "261": "Sophia Loren’s Appreciation Day",
               "262": "International Talk Like a Pirate Day",
               "263": "Amoeba Assimilation Day",
               "264": "Sarcasm Day",
               "265": "Believe the Impossible Day",
               "266": "Albino Appreciation Day",
               "267": "Cocktail Day",
               "268": "Any Port & Lemon in a Storm Day",
               "269": "Scrub the Poop Deck Day",
               "270": "Insult a Narcissist Day",
               "271": "Fictional Character Day",
               "272": "Double Entendre Day",
               "273": "Plan for 31st Sept Day",
               "274": "Agnolotti Appreciation Day",
               "275": "Noodle Day",
               "276": "Eccentricity Appreciation Day",
               "277": "Fortified Wines Day",
               "278": "Slighlty Naughty Day",
               "279": "International Pastafarian Headgear Day",
               "280": "Quob Day",
               "281": "Tell Massive Lies Day",
               "282": "Knot Day",
               "283": "Dildo Day",
               "284": "Play Nice Day",
               "285": "Wanting Wonton Day",
               "286": "Arrabiata Sauce Day",
               "287": "World Food Day",
               "288": "Another Noodle Day",
               "289": "Blue Whale Contemplation Day",
               "290": "World Pasta Day",
               "291": "Irony Day",
               "292": "Try Not to Die Day",
               "293": "To Excess and No Further Day",
               "294": "Try Thinking Day",
               "295": "Intergalactic Peeing Competition",
               "296": "Strip for your Lover Day",
               "297": "Cider Appreciation Day",
               "298": "World Pasta Day",
               "299": "Silly Walks Day",
               "300": "Clam Sauce Day",
               "301": "Extra Kinky Day",
               "302": "Nut Day",
               "303": "Halloween",
               "304": "Gerbil Caressing Day",
               "305": "Moustache Appreciation Day",
               "306": "Rigatoni Day",
               "307": "Kissing Frogs Day",
               "308": "Not the Zombie Apocalypse Day",
               "309": "Oral Sex Day",
               "310": "Dodo Grieving Day",
               "311": "Tentacle Day",
               "312": "Appreciate Your Loved Ones Day",
               "313": "Odd Socks Day",
               "314": "Look on the Bright Side of Life Day",
               "315": "Small Furry Creatures Appreciation Day",
               "316": "Drunk Creation Contemplation Day",
               "317": "Punch a Pigeon Day",
               "318": "Laugh like a Lunatic Day",
               "319": "Awkwardly Honest Day",
               "320": "Extinct Species Memorial Day",
               "321": "Al Dente Day",
               "322": "Talk like Donald Duck Day",
               "323": "World Toilet Day",
               "324": "Say no to Cannibalism Day",
               "325": "Register a Complaint Day",
               "326": "Blackbeard Memorial Day",
               "327": "General Debauchery Day",
               "328": "Undead Understanding Day",
               "329": "Lucy the Australopithecine Discovery Day",
               "330": "Racist Depreciation Day",
               "331": "Grog Guzzling Day",
               "332": "Blue Cheese Day",
               "333": "Cutlass Sharpening Day",
               "334": "Gnome Awareness Day",
               "335": "Marijuana Sauce Day",
               "336": "Fart Like a Pirate Day",
               "337": "International Say No to Selfies Day",
               "338": "Vibrator Day",
               "339": "Remember the Spanish Inquisition Day",
               "340": "Pirate Appreciation Day",
               "341": "Still Not Dead Day",
               "342": "Garlic Bread Day",
               "343": "Noodle Ring Day",
               "344": "International Human Rights Day",
               "345": "International Shareware Day",
               "346": "Ice Cream Day",
               "347": "Monkey Day",
               "348": "Cat Herders Day",
               "349": "Stupid Toy Day",
               "350": "Beethoven’s Birthday",
               "351": "Sloth Day",
               "352": "Underdog Day",
               "353": "Dalek Remembrance Day",
               "354": "Swashbuckling Day",
               "355": "Saturnalia",
               "356": "Marco Polo Day",
               "357": "Festivus",
               "358": "Egg Nog Day",
               "359": "1st Day of Noodlemas",
               "360": "Cardbard Box Appreciation Day",
               "361": "3rd Day of Noodlemas",
               "362": "Only 4 Pasta-eating Days Left This Year Day",
               "363": "Yad sdrawckab",
               "364": "Get Drunk Early for Hogmanay",
               "365": "Hogmanay",
}
